// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIetth0uTjfLH3JYY78APWSRLK7fa9SAA',
    appId: '1:350581455482:web:21fb8f9d4cd39f7305d9c3',
    messagingSenderId: '350581455482',
    projectId: 'egot-hand-sign-alpha-language',
    authDomain: 'egot-hand-sign-alpha-language.firebaseapp.com',
    databaseURL: 'https://egot-hand-sign-alpha-language-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'egot-hand-sign-alpha-language.firebasestorage.app',
    measurementId: 'G-GPCRXT4MVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq1vvYYie9KNkV_YnTw4K7i4oAw41V-e8',
    appId: '1:350581455482:android:a2892edfac63d13005d9c3',
    messagingSenderId: '350581455482',
    projectId: 'egot-hand-sign-alpha-language',
    databaseURL: 'https://egot-hand-sign-alpha-language-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'egot-hand-sign-alpha-language.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgUeHYP9fIXEtI3YfjQu2_kpd4InHpnV0',
    appId: '1:350581455482:ios:f504dc6633ccfc2305d9c3',
    messagingSenderId: '350581455482',
    projectId: 'egot-hand-sign-alpha-language',
    databaseURL: 'https://egot-hand-sign-alpha-language-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'egot-hand-sign-alpha-language.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgUeHYP9fIXEtI3YfjQu2_kpd4InHpnV0',
    appId: '1:350581455482:ios:f504dc6633ccfc2305d9c3',
    messagingSenderId: '350581455482',
    projectId: 'egot-hand-sign-alpha-language',
    databaseURL: 'https://egot-hand-sign-alpha-language-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'egot-hand-sign-alpha-language.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIetth0uTjfLH3JYY78APWSRLK7fa9SAA',
    appId: '1:350581455482:web:57040a87f1fcc2a305d9c3',
    messagingSenderId: '350581455482',
    projectId: 'egot-hand-sign-alpha-language',
    authDomain: 'egot-hand-sign-alpha-language.firebaseapp.com',
    databaseURL: 'https://egot-hand-sign-alpha-language-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'egot-hand-sign-alpha-language.firebasestorage.app',
    measurementId: 'G-822P19N3H5',
  );

}